# Generated by Django 4.1.5 on 2023-01-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_restaurant_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_of_restourant',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='restourant_name', to='main.restaurant'),
        ),
    ]
